services:
  - type: web
    name: valentinesDays
    env: node
    repo: https://github.com/karanveerSsingh/valentinesDays.git
    branch: main
    buildCommand: npm install && npm run build
    startCommand: node server.js
